### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by ernestorocha** [rzymek/meteor-moment#4]
I'm now seeing this error, sometimes happens when server is reloading due changes in development:

```
W20150324-07:24:52.640(-3)? (STDERR) TypeError: Cannot call method 'defineLocale' of undefined
W20150324-07:24:52.640(-3)? (STDERR)     at Package (packages/rzymek:moment-locale-de/locale.js:29:1)
W20150324-07:24:52.640(-3)? (STDERR)     at format.m (packages/rzymek:moment-locale-de/locale.js:12:1)
```

The problem seems to be that `moment` is not being loaded before your package:
```
return moment.defineLocale('de', {                                    // 29
```
Any idea ? This can be related to the fact that `moment` was updated to 2.9.0 ?

**Comment by rzymek** [comment]
Show me your `.meteor/versions` file, please.

**Comment by ernestorocha** [comment]
Sure, here:

```
accounts-base@1.2.0
accounts-oauth@1.1.4
accounts-password@1.1.0
ajduke:bootstrap-tokenfield@0.3.2
alamont:chartjs@0.0.9
alanning:roles@1.2.13
aldeed:autoform@4.2.2
aldeed:collection2@2.3.2
aldeed:simple-schema@1.3.1
aldeed:template-extension@3.1.1
alethes:pages@1.7.2
anti:i18n@0.4.3
autoupdate@1.2.0
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.0
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
cfs:access-point@0.1.45
cfs:base-package@0.0.28
cfs:collection@0.5.5
cfs:collection-filters@0.2.4
cfs:data-man@0.0.6
cfs:file@0.1.16
cfs:filesystem@0.1.2
cfs:graphicsmagick@0.0.18
cfs:http-methods@0.0.27
cfs:http-publish@0.0.13
cfs:power-queue@0.9.11
cfs:reactive-list@0.0.9
cfs:reactive-property@0.0.4
cfs:s3@0.1.3
cfs:standard-packages@0.5.5
cfs:storage-adapter@0.2.1
cfs:tempstore@0.1.4
cfs:upload-http@0.0.20
cfs:worker@0.1.4
check@1.0.5
chfritz:cryptojs-hmac-md5@0.1.0
chuangbo:cookie@1.1.0
classcraft:imagemagick@0.9.1
cmather:handlebars-server@2.0.0
coffeescript@1.0.6
copleykj:livestamp@1.1.6
d3@1.0.0
dandv:caret-position@2.1.0-3
dburles:collection-helpers@1.0.2
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
email@1.0.6
facebook@1.1.4
fastclick@1.0.3
flowkey:bootstrap-tour@1.0.0
fourseven:scss@2.0.0-beta_1
geojson-utils@1.0.3
handlebars@1.0.3
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
ian:accounts-ui-bootstrap-3@1.2.37
id-map@1.0.3
iron:controller@1.0.7
iron:core@1.0.7
iron:dynamic-template@1.0.7
iron:layout@1.0.7
iron:location@1.0.7
iron:middleware-stack@1.0.7
iron:router@1.0.7
iron:url@1.0.7
jquery@1.11.3_2
json@1.0.3
launch-screen@1.0.2
less@1.0.13
livedata@1.0.13
localstorage@1.0.3
logging@1.0.7
matb33:collection-hooks@0.7.11
matteodem:easy-search@1.4.13
matteodem:server-session@0.4.2
meteor@1.1.5
meteor-platform@1.2.2
meteorhacks:fast-render@2.3.1
meteorhacks:inject-data@1.2.2
meteorhacks:inject-initial@1.0.0
meteorhacks:kadira@2.20.1
meteorhacks:kadira-binary-deps@1.3.1
meteorhacks:kadira-profiler@1.0.2
meteorhacks:meteorx@1.3.1
meteorhacks:picker@1.0.1
meteorhacks:zones@1.4.0
minifiers@1.1.4
minimongo@1.0.7
mizzao:autocomplete@0.5.1
mobile-status-bar@1.0.3
momentjs:moment@2.9.0
monbro:mongodb-mapreduce-aggregation@1.0.1
mongo@1.1.0
mongo-livedata@1.0.8
mrt:jquery-jcrop@0.0.3
mrt:nprogress@0.1.0
mrt:smart-publish@0.2.0
natestrauser:select2@3.5.1
natestrauser:x-editable-bootstrap@1.5.2_2
nemo64:bootstrap@3.3.1_1
nemo64:bootstrap-data@3.3.1_1
npm-bcrypt@0.7.8_1
oauth@1.1.4
oauth2@1.1.3
observe-sequence@1.0.5
ordered-dict@1.0.3
raix:eventemitter@0.1.1
raix:handlebar-helpers@0.2.4
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
reywood:iron-router-ga@0.5.3
reywood:publish-composite@1.3.5
routepolicy@1.0.5
rzymek:moment-locale-de@2.8.4
rzymek:moment-locale-pt-br@2.8.4
sacha:spin@2.0.4
sayawan:pickadate@3.3.1
sergeyt:typeahead@0.10.5_13
service-configuration@1.0.4
session@1.1.0
sha@1.0.3
spacebars@1.0.6
spacebars-compiler@1.0.5
srp@1.0.3
standard-app-packages@1.0.5
stylus@1.0.7
templating@1.1.0
tracker@1.0.6
tsega:bootstrap3-lightbox@0.2.0
ui@1.0.6
underscore@1.0.3
url@1.0.4
vicentealencar:cordova-fb@1.1.9
vsivsi:job-collection@1.0.0
webapp@1.2.0
webapp-hashing@1.0.3
yogiben:admin@1.1.0
yogiben:pretty-email@0.0.3
```

**Comment by rzymek** [comment]
Yeah, it might have to do with momentjs at version 2.9.0.
I've published an update of locales to 2.9.0. Let me know if you still have a problem after `meteor update`

**Comment by ernestorocha** [comment]
Great!

Thanks!

**Comment by ernestorocha** [comment]
Hm... I'm still facing the same problem. That's pretty strange. I'll try to debug later.

**Comment by pmuens** [comment]
It seems that the Version 2.9.0 is not on Atmosphere. Can you please republish it?

**Comment by rzymek** [comment]
@pmuens - Right, missed that one. Fixed. [Version 2.9.0 published](https://atmospherejs.com/rzymek/moment-locales).

**Comment by pmuens** [comment]
Thanks! :+1:
